SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS
LEFT JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE LIKE 'INTACT%'
    AND (OUTS.SEX_UPON_OUTCOME LIKE 'SPAYED%' OR OUTS.SEX_UPON_OUTCOME LIKE 'NEUTERED%')
ORDER BY INS.ANIMAL_ID